sudo: required
language: c

env:
  global:
    - DEPLOY_USER=delta DEPLOY_SERVER="py.delta.chat"

  matrix:
    - MESONARGS="" DOCS=t TESTS=t
    - MESONARGS="-Dmonolith=true" TESTS=t
    - MESONARGS="--default-library=static"
    - MESONARGS="--wrap-mode=forcefallback --default-library=static"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    # for newer doxygen: - sourceline: 'ppa:libreoffice/ppa'
    packages:
    - python3-pip
    - python3.5
    - g++-7
    - libssl-dev
    - libsqlite3-dev
    - libbz2-dev
    - zlib1g-dev
    - python3.5-dev
    - python-software-properties
    - doxygen

install:
  - export CC=gcc-7
  - export CXX=g++-7
  - sudo ln -sf /usr/bin/python3.5 /usr/bin/python3
  - sudo pip3 install meson
  - wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
  - unzip ninja-linux.zip
  - sudo cp ninja /usr/bin
  - wget http://http.debian.net/debian/pool/main/c/cyrus-sasl2/cyrus-sasl2_2.1.27~101-g0780600+dfsg.orig.tar.xz
  - tar xfv cyrus-sasl2_2.1.27~101-g0780600+dfsg.orig.tar.xz
  - pushd cyrus-sasl2-2.1.27~101-g0780600+dfsg.orig && ./autogen.sh && make && sudo make install && popd

script:
  - doxygen --version
  - mkdir -p builddir && pushd builddir
  - meson $MESONARGS && ninja -v && sudo ninja install
  - export LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
  - sudo ldconfig -v
  - popd && pushd docs
  - if [ -n "$DOCS" ]; then doxygen; fi
  - popd && pushd python
  - virtualenv -p /usr/bin/python3.5 venv
  - source venv/bin/activate
  - pip install tox
  - if [ -e /usr/local/lib/x86_64-linux-gnu/libdeltachat.so ]; then ldd /usr/local/lib/x86_64-linux-gnu/libdeltachat.so; fi
  - if [ -n "$TESTS" ]; then tox; fi
  - if [ -n "$DOCS" ]; then tox -e doc; fi
  - popd

deploy:
  provider: script
  skip_cleanup: true
  script: bash $TRAVIS_BUILD_DIR/.scripts/deploy.sh
  on:
    all_branches: true
    condition: $DOCS
