name: CI
on:
  push:

permissions: {}

jobs:
  build:
    runs-on: xcode-27
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          show-progress: false
          persist-credentials: false
      - run: cargo install cargo-lipo
      - run: pod install
      - run: set -o pipefail && xcodebuild -workspace deltachat-ios.xcworkspace -scheme deltachat-ios -destination "platform=iOS Simulator,name=iPhone 18 Pro,OS=latest" test | xcbeautify --renderer github-actions
